module.exports = {
    extends: ['@commitlint/config-conventional'],
    rules: {
        'type-enum': [
            2,
            'always',
            [
                'feat',
                'fix',
                'docs',
                'style',
                'refactor',
                'perf',
                'test',
                'build',
                'ci',
                'chore',
                'revert',
            ],
        ],
        'subject-case': [0, 'never'],
        'subject-full-stop': [0, 'never'],
    },
    // cz-git 配置
    prompt: {
        messages: {
            type: '选择你要提交的类型 :',
            scope: '选择一个提交范围（可选）:',
            customScope: '请输入自定义的提交范围 :',
            subject: '填写简短精炼的变更描述 :',
            body: '填写详细描述（可选）。使用 "|" 换行 :',
            breaking: '列出任何突破性变更（可选）。使用 "|" 换行 :',
            footerPrefixsSelect: '选择关联issue前缀（可选）:',
            customFooterPrefixs: '输入自定义issue前缀 :',
            footer: '列出关联issue (可选) 例如: #31, #I3244 :',
            confirmCommit: '确认提交？',
        },
        types: [
            { value: 'feat', name: '✨ feat:     新增功能', emoji: '✨' },
            { value: 'fix', name: '🐛 fix:      修复bug', emoji: '🐛' },
            { value: 'docs', name: '📝 docs:     文档变更', emoji: '📝' },
            { value: 'style', name: '💄 style:    代码格式（不影响功能）', emoji: '💄' },
            {
                value: 'refactor',
                name: '♻️  refactor: 代码重构（不包括bug修复或功能添加）',
                emoji: '♻️',
            },
            { value: 'perf', name: '⚡️ perf:     性能优化', emoji: '⚡️' },
            { value: 'test', name: '✅ test:     测试相关', emoji: '✅' },
            { value: 'build', name: '🏗️  build:    构建相关', emoji: '🏗️' },
            { value: 'ci', name: '🔧 ci:       CI/CD配置变更', emoji: '🔧' },
            { value: 'chore', name: '🗯️  chore:    其他变更（不影响代码）', emoji: '🗯️' },
            { value: 'revert', name: '⏪️  revert:   回滚提交', emoji: '⏪️' },
        ],
        useEmoji: true,
        emojiAlign: 'center',
        themeColorCode: '',
        scopes: [],
        allowCustomScopes: true,
        allowEmptyScopes: true,
        customScopesAlign: 'bottom',
        customScopesAlias: 'custom',
        emptyScopesAlias: 'empty',
        upperCaseSubject: false,
        allowBreakingChanges: ['feat', 'fix'],
        breaklineNumber: 100,
        breaklineChar: '|',
        skipQuestions: [],
        issuePrefixs: [{ value: 'closed', name: 'closed:   关闭issue' }],
        customIssuePrefixsAlign: 'top',
        emptyIssuePrefixsAlias: 'skip',
        customIssuePrefixsAlias: 'custom',
        allowCustomIssuePrefixs: true,
        allowEmptyIssuePrefixs: true,
        confirmColorize: true,
        maxHeaderLength: Infinity,
        maxSubjectLength: Infinity,
        minSubjectLength: 0,
        scopeOverrides: undefined,
        defaultBody: '',
        defaultIssues: '',
        defaultScope: '',
        defaultSubject: '',
    },
};
