import type { Metadata } from 'next';
// 导入全局样式文件
import './globals.css';
import { AuthProvider } from './providers/auth-provider';
import { HeroUIProvider } from '@heroui/react';

export const metadata: Metadata = {
    title: '基金监测列表',
    description: 'Generated by Kamal',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="zh-CN" data-oid="nkt6ee.">
            <body className="" data-oid=":skcoqk">
                <HeroUIProvider>
                    <AuthProvider>{children}</AuthProvider>
                </HeroUIProvider>
            </body>
        </html>
    );
}
