import type { Metadata } from 'next';
import './globals.css';
import { AuthProvider } from './providers/auth-provider';

export const metadata: Metadata = {
    title: '基金监测列表',
    description: 'Generated by Kamal',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="zh-CN" data-oid="nkt6ee.">
            <body className="" data-oid=":skcoqk">
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    );
}
