import type { Metadata } from 'next';
// 导入全局样式文件
import './globals.css';
import ClientProviders from './providers/client-providers';

export const metadata: Metadata = {
    title: '基金监测列表',
    description: 'Generated by Kamal',
};

// 定时任务初始化逻辑已移至CronTaskInitializer组件

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="zh-CN">
            <body className="">
                <ClientProviders>{children}</ClientProviders>
            </body>
        </html>
    );
}
